### ISSUE TITLE
Periodic calls for entries

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/awesome-orbitdb#6]
Proposal: We should, at a fixed interval, ask for new entries to this repo. Maybe once a month? We can post it on gitter, discord, IRC, matrix, etc.

**Comment by RichardLitt** [comment]
I like this idea. We could add it to the note template: "Hey, anyone see anything great to add to awesome-orbitdb?". What do you think about that idea? It's basically a twice a month check.

**Comment by aphelionz** [comment]
Sounds great.
